
inherit_from: .rubocop_airbnb.yml

ClassAndModuleChildren:
  Enabled: false

Rails:
  Enabled: true

LineLength:
  Max: 130lin

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'

Style/AsciiComments:
  Enabled: false